---
title: "Introduction"
author: ""
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The Salem package is based on the 
[The Salem Withcraft Website](https://www.tulane.edu/~salem/) created by
Richard Latner.  The package includes all of the data sets from the website
as R data frames.  The data have been reorganized from the original structure
for ease of use in R.  (Copies of the original tab delimited raw data sets
are available both at the Salem Witchcraft site and in the github respository
for this package.)  



### References

A detailed discussion of the data sources can be found on the
[ the notes page of the website](https://www.tulane.edu/~salem/Notes.html).
.

A list of scholarly sources about the Salem witch trials (through about 2008)
is on the [bibliography page](https://www.tulane.edu/~salem/Bibliography.html).

An updated list of reference website links from the bibliography page 
is given here.

 - [A Guide to the On-Line Primary Sources of the Salem Witch Trials](http://www.17thc.us/primarysources/)
 - [Danvers Archival Center](https://www.danverslibrary.org/archive/welcome-to-the-danvers-archival-center-website/)
 - [Famous Trials: Salem Witchcraft Trials (1692)] (https://famous-trials.com/salem)
 - [Salem Witch Trials: Documentary Archive and Transcription Project](http://salem.lib.virginia.edu/home.html)
 
 
 #### Here are some additional scholarly sources
 
 
 